### ISSUE TITLE
Native invocation fails when warp is enabled

### ISSUE THREAD

**Issue by ShomyTKD** [Qbox-project/qbx-garbagejob#21]
### Summary

Garbage truck spawns, but netId is nil and error is displayed in the server console

### Reproduction

1. Give yourself a garbage job
2. Go to the ped and request a route

### Expected behavior

When being warped inside the garbage truck, your vehicle should be fueled to the maximum and there shouldn't be any errors in the server console.

### Actual behavior

Once a route is requested, you are warped inside the garbage truck. Everything seems to be working, but an error is thrown in the server console. Client console is also throwing warnings about entity id.

![image](https://github.com/Qbox-project/qbx_garbagejob/assets/26857315/d35f7cc8-59ad-4558-9eb6-5ffc00cdf3be)
![image](https://github.com/Qbox-project/qbx_garbagejob/assets/26857315/8ba617c3-310a-4a6b-ab2c-22fbc0c216ca)

### Additional context

I worked on this with solareon and we came to the conclusion that the problem lies on callback garbagejob:server:spawnVehicle, precisely here:
`local netId, veh = qbx.spawnVehicle({ spawnSource = coords, model = joaat(config.vehicle), warp = source })`

When the `warp = source` is passed, the error is thrown. It seems to fail inside the `qbx.spawnVehicle` function when trying to set a bucket `bucket = GetEntityRoutingBucket(ped) or nil`. This prevents the return of `netId` and `veh`, resulting in the error.

If you remove `warp = source`, everything works flawlessly.

### Current Version

v1.0.0 (latest)

### Custom Resources

No, I have a fresh install of Qbox

**Comment by Manason** [comment]
Not sure if this is a bug in our documentation, or code, but I believe that warpSource needs to be the ped id, not the server id
